=== tuttiq/webclinica-docs/Material_de_apoio/Software/CID10XML/CID-O.dtd
<!ELEMENT document (cid-o)>

<!ELEMENT cid-o (grupo+)>
	<!ELEMENT grupo (nome, referencias?, (grupo|categoria)+)>
	<!ATTLIST grupo codgrupo NMTOKEN #REQUIRED>
	<!ATTLIST grupo inicial NMTOKEN #REQUIRED>
	<!ATTLIST grupo final   NMTOKEN #REQUIRED>
		<!ELEMENT categoria (nome, nota*, referencias?)>
		<!ATTLIST categoria codcat CDATA #REQUIRED>

	
<!ELEMENT referencias (referencia*)>
	<!ELEMENT referencia (#PCDATA)>
		<!ATTLIST referencia codrefer NMTOKEN #IMPLIED>
	
<!ELEMENT nome (#PCDATA)>

<!ELEMENT nota (#PCDATA)>

=== tuttiq/webclinica-docs/Material_de_apoio/Software/CID10XML/CID-O.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>

<!--
<?xml-stylesheet type="text/xsl" href="CID-O.xsl"?>
<?xml-stylesheet type="text/xsl" href="CID-O-cnv-grupos.xsl"?>
<?xml-stylesheet type="text/xsl" href="CID-O-cnv-grupos-sel.xsl"?>
<?xml-stylesheet type="text/xsl" href="CID-O-cnv-grupos-categorias.xsl"?>
<?xml-stylesheet type="text/xsl" href="CID-O-cnv-categorias.xsl"?>
<?xml-stylesheet type="text/xsl" href="CID-O-csv-grupos.xsl"?>
<?xml-stylesheet type="text/xsl" href="CID-O-csv-categorias.xsl"?>
-->

<!DOCTYPE cid-o SYSTEM "CID-O.dtd">
<cid-o>
	<grupo codgrupo="M800-M800" inicial="M800" final="M800">
		<nome>Neoplasias SOE</nome>
		<categoria codcat="M8000/0">
			<nome>Neoplasia benigna</nome>
			</categoria>
		<categoria codcat="M8000/1">
			<nome>Neoplasia de comportamento incerto se benigno ou maligno</nome>
			</categoria>
		<categoria codcat="M8000/3">
			<nome>Neoplasia maligna</nome>
			</categoria>
		<categoria codcat="M8000/6">
			<nome>Neoplasia metastática</nome>
			</categoria>
		<categoria codcat="M8001/0">
			<nome>Células tumorais, benignas</nome>
			</categoria>
		<categoria codcat="M8001/1">
			<nome>Células tumorais, incerto se benignas ou malignas</nome>
			</categoria>
		<categoria codcat="M8001/3">
			<nome>Células tumorais malignas</nome>
			</categoria>
		<categoria codcat="M8002/3">
			<nome>Tumor maligno, tipo de células pequenas</nome>
			</categoria>
		<categoria codcat="M8003/3">
			<nome>Tumor maligno, tipo de células gigantes</nome>
			</categoria>
		<categoria codcat="M8004/3">
			<nome>Tumor maligno, tipo de células fusiformes</nome>
			</categoria>
		</grupo>
	<grupo codgrupo="M801-M804" inicial="M801" final="M804">
		<nome>Neoplasias epiteliais SOE</nome>
		<categoria codcat="M8010/0">
			<nome>Tumor epitelial benigno</nome>
			</categoria>
		<categoria codcat="M8010/2">
			<nome>Carcinoma in situ SOE</nome>
			</categoria>
		<categoria codcat="M8010/3">
			<nome>Carcinoma SOE</nome>
			</categoria>
		<categoria codcat="M8010/6">
			<nome>Carcinoma metastático SOE</nome>
			</categoria>
		<categoria codcat="M8011/0">
			<nome>Epitelioma benigno</nome>
			</categoria>
		<categoria codcat="M8011/3">
			<nome>Epitelioma maligno</nome>
			</categoria>
		<categoria codcat="M8012/3">
			<nome>Carcinomas de células grandes SOE</nome>
			</categoria>
		<categoria codcat="M8020/3">
			<nome>Carcinoma indiferenciado SOE</nome>
			</categoria>
		<categoria codcat="M8021/3">
			<nome>Carcinoma anaplásico SOE</nome>
			</categoria>
		<categoria codcat="M8022/3">
			<nome>Carcinoma pleomórfico</nome>
			</categoria>
		<categoria codcat="M8030/3">
			<nome>Carcinoma de células gigantes e de células fusiformes</nome>
			</categoria>
		<categoria codcat="M8031/3">
			<nome>Carcinoma de células gigantes</nome>
			</categoria>
		<categoria codcat="M8032/3">
			<nome>Carcinoma de células fusiformes</nome>
			</categoria>
		<categoria codcat="M8033/3">
			<nome>Carcinoma pseudossarcomatoso</nome>
			</categoria>
		<categoria codcat="M8034/3">
			<nome>Carcinoma de células poligonais</nome>
			</categoria>
		<categoria codcat="M8040/1">
			<nome>&quot;Tumorlet&quot;</nome>
			</categoria>
		<categoria codcat="M8041/3">
			<nome>Carcinoma de células pequenas SOE</nome>
			</categoria>
		<categoria codcat="M8042/3">
			<nome>Carcinoma &quot;oat cell&quot;</nome>
			<referencias>
				<referencia codrefer="C34">C34.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8043/3">
			<nome>Carcinoma de células pequenas, fusiformes</nome>
			<referencias>
				<referencia codrefer="C34">C34.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8044/3">
			<nome>Carcinoma de células pequenas, intermediárias</nome>
			<referencias>
				<referencia codrefer="C34">C34.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8045/3">
			<nome>Carcinoma de células pequenas e de células grandes</nome>
			<referencias>
				<referencia codrefer="C34">C34.-</referencia>
				</referencias>
			</categoria>
		</grupo>
	<grupo codgrupo="M805-M808" inicial="M805" final="M808">
		<nome>Neoplasias de células escamosas</nome>
		<categoria codcat="M8050/0">
			<nome>Papiloma SOE</nome>
			<nota>exceto Papiloma de bexiga M8120/1</nota>
			</categoria>
		<categoria codcat="M8050/2">
			<nome>Carcinoma papilar in situ</nome>
			</categoria>
		<categoria codcat="M8050/3">
			<nome>Carcinoma papilar SOE</nome>
			</categoria>
		<categoria codcat="M8051/0">
			<nome>Papiloma verrucoso</nome>
			</categoria>
		<categoria codcat="M8051/3">
			<nome>Carcinoma verrucoso SOE</nome>
			</categoria>
		<categoria codcat="M8052/0">
			<nome>Papiloma de células escamosas</nome>
			</categoria>
		<categoria codcat="M8052/3">
			<nome>Carcinoma papilar de células escamosas</nome>
			</categoria>
		<categoria codcat="M8053/0">
			<nome>Papiloma invertido</nome>
			</categoria>
		<categoria codcat="M8060/0">
			<nome>Papilomatose SOE</nome>
			</categoria>
		<categoria codcat="M8070/2">
			<nome>Carcinoma in situ de células escamosas, SOE</nome>
			</categoria>
		<categoria codcat="M8070/3">
			<nome>Carcinoma de células escamosas SOE</nome>
			</categoria>
		<categoria codcat="M8070/6">
			<nome>Carcinoma de células escamosas, metastático, SOE</nome>
			</categoria>
		<categoria codcat="M8071/3">
			<nome>Carcinoma de células escamosas, queratinizado, SOE</nome>
			</categoria>
		<categoria codcat="M8072/3">
			<nome>Carcinoma de células escamosas, de células grandes, não queratinizado</nome>
			</categoria>
		<categoria codcat="M8073/3">
			<nome>Carcinoma de células escamosas, de células pequenas, não queratinizado</nome>
			</categoria>
		<categoria codcat="M8074/3">
			<nome>Carcinoma de células escamosas, de células fusiformes</nome>
			</categoria>
		<categoria codcat="M8075/3">
			<nome>Carcinoma de células escamosas adenóides</nome>
			</categoria>
		<categoria codcat="M8076/2">
			<nome>Carcinoma in situ de células escamosas com invasão questionável do estroma</nome>
			<referencias>
				<referencia codrefer="C53">C53.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8076/3">
			<nome>Carcinoma de células escamosas, microinvasivo</nome>
			<referencias>
				<referencia codrefer="C53">C53.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8077/2">
			<nome>Neoplasia intra-epitelial, grau III, de colo uterino, vulva e vagina</nome>
			</categoria>
		<categoria codcat="M8080/2">
			<nome>Eritroplasia de Queyrat</nome>
			</categoria>
		<categoria codcat="M8081/2">
			<nome>Doença de Bowen</nome>
			<referencias>
				<referencia codrefer="C44">C44.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8082/3">
			<nome>Carcinoma linfoepitelial</nome>
			</categoria>
		</grupo>
	<grupo codgrupo="M809-M811" inicial="M809" final="M811">
		<nome>Neoplasias de células basais</nome>
		<categoria codcat="M8090/1">
			<nome>Tumor de células basais</nome>
			<referencias>
				<referencia codrefer="D48.5">D48.5</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8090/3">
			<nome>Carcinoma de células basais SOE</nome>
			<referencias>
				<referencia codrefer="C44">C44.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8091/3">
			<nome>Carcinoma de células basais, multicêntrico</nome>
			<referencias>
				<referencia codrefer="C44">C44.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8092/3">
			<nome>Carcinoma de células basais, tipo morféia</nome>
			<referencias>
				<referencia codrefer="C44">C44.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8093/3">
			<nome>Carcinoma de células basais, fibroepitelial</nome>
			<referencias>
				<referencia codrefer="C44">C44.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8094/3">
			<nome>Carcinoma basoescamoso</nome>
			<referencias>
				<referencia codrefer="C44">C44.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8095/3">
			<nome>Carcinoma metatípico</nome>
			<referencias>
				<referencia codrefer="C44">C44.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8096/0">
			<nome>Epitelioma intra-epidérmico de Jadassohn</nome>
			<referencias>
				<referencia codrefer="D23">D23.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8100/0">
			<nome>Tricoepitelioma</nome>
			<referencias>
				<referencia codrefer="D23">D23.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8101/0">
			<nome>Tricofoliculoma</nome>
			<referencias>
				<referencia codrefer="D23">D23.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8102/0">
			<nome>Tricolemoma</nome>
			<referencias>
				<referencia codrefer="D23">D23.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8110/0">
			<nome>Pilomatrixoma SOE</nome>
			<referencias>
				<referencia codrefer="D23">D23.-</referencia>
				</referencias>
			</categoria>
		<categoria codcat="M8110/3">
			<nome>Carcinoma da pilomátrix</nome>
			<referencias>
				<referencia codrefer="C44">C44.-</referencia>
				</referencias>
			</categoria>
		</grupo>
	<grupo codgrupo="M812-M813" inicial="M812" final="M813">
		<nome>Papilomas e carcinomas de células de transição</nome>
		<categoria codcat="M8120/0">
			<nome>Papiloma de células de transição, SOE</nome>
			</categoria>
		<categoria codcat="M8120/1">
			<nome>Papiloma urotelial</nome>
			</categoria>
		<categoria codcat="M8120/2">
			<nome>Carcinoma in situ de células transicionais</nome>
			</categoria>
		<categoria codcat="M8120/3">
