=== tuttiq/webclinica-docs/Material_de_apoio/Software/CID10XML/Listas.dtd
<!ELEMENT document (listas)>

<!ELEMENT listas (lista+)>
	<!ELEMENT lista (nome, tipo?, item+)>
		<!ELEMENT item (nome, codigos+, item*)>
		<!ATTLIST item seq NMTOKEN #REQUIRED>

<!ELEMENT nome (#PCDATA)>

<!ELEMENT tipo (#PCDATA)>

<!ELEMENT codigos (#PCDATA)>

=== tuttiq/webclinica-docs/Material_de_apoio/Software/CID10XML/Listas.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>

<!-- 
<?xml-stylesheet type="text/xsl" href="Listas-cnv.xsl"?>
<?xml-stylesheet type="text/xsl" href="Listas-cnv-sel.xsl"?>
-->

<!DOCTYPE listas SYSTEM "Listas.dtd">
<listas>
	<lista>
		<nome>Mortalidade Geral  - Lista Condensada</nome>
		<item seq="1-001">
			<nome>Algumas doenças infecciosas e parasitárias</nome>
			<codigos>A00-B99</codigos>
			<item seq="1-002">
				<nome>Cólera</nome>
				<codigos>A00-A00</codigos>
				</item>
			<item seq="1-003">
				<nome>Diarréia e gastroenterite de origem infecciosa presumível</nome>
				<codigos>A09-A09</codigos>
				</item>
			<item seq="1-004">
				<nome>Outras doenças infecciosas intestinais</nome>
				<codigos>A01-A08</codigos>
				</item>
			<item seq="1-005">
				<nome>Tuberculose respiratória</nome>
				<codigos>A15-A16</codigos>
				</item>
			<item seq="1-006">
				<nome>Outras tuberculoses</nome>
				<codigos>A17-A19</codigos>
				</item>
			<item seq="1-007">
				<nome>Peste</nome>
				<codigos>A20-A20</codigos>
				</item>
			<item seq="1-008">
				<nome>Tétano</nome>
				<codigos>A33-A35</codigos>
				</item>
			<item seq="1-009">
				<nome>Difteria</nome>
				<codigos>A36-A36</codigos>
				</item>
			<item seq="1-010">
				<nome>Coqueluche</nome>
				<codigos>A37-A37</codigos>
				</item>
			<item seq="1-011">
				<nome>Infecção meningocócica</nome>
				<codigos>A39-A39</codigos>
				</item>
			<item seq="1-012">
				<nome>Septicemia</nome>
				<codigos>A40-A41</codigos>
				</item>
			<item seq="1-013">
				<nome>Infecções com transmissão predominantemente sexual</nome>
				<codigos>A50-A64</codigos>
				</item>
			<item seq="1-014">
				<nome>Poliomielite aguda</nome>
				<codigos>A80-A80</codigos>
				</item>
			<item seq="1-015">
				<nome>Raiva</nome>
				<codigos>A82-A82</codigos>
				</item>
			<item seq="1-016">
				<nome>Febre amarela</nome>
				<codigos>A95-A95</codigos>
				</item>
			<item seq="1-017">
				<nome>Outras febres por arbovírus e febres hemorrágicas virais</nome>
				<codigos>A90-A94</codigos>
				<codigos>A96-A99</codigos>
				</item>
			<item seq="1-018">
				<nome>Sarampo</nome>
				<codigos>B05-B05</codigos>
				</item>
			<item seq="1-019">
				<nome>Hepatite viral</nome>
				<codigos>B15-B19</codigos>
				</item>
			<item seq="1-020">
				<nome>Doença pelo vírus da imunodeficiência humana [HIV]</nome>
				<codigos>B20-B24</codigos>
				</item>
			<item seq="1-021">
				<nome>Malária</nome>
				<codigos>B50-B54</codigos>
				</item>
			<item seq="1-022">
				<nome>Leishmaniose</nome>
				<codigos>B55-B55</codigos>
				</item>
			<item seq="1-023">
				<nome>Tripanossomíase</nome>
				<codigos>B56-B57</codigos>
				</item>
			<item seq="1-024">
				<nome>Esquistossomose</nome>
				<codigos>B65-B65</codigos>
				</item>
			<item seq="1-025">
				<nome>Restante de algumas doenças infecciosas e parasitárias</nome>
				<codigos>A21-A32</codigos>
				<codigos>A38-A38</codigos>
				<codigos>A42-A49</codigos>
				<codigos>A65-A79</codigos>
				<codigos>A81-A81</codigos>
				<codigos>A83-A89</codigos>
				<codigos>B00-B04</codigos>
				<codigos>B06-B09</codigos>
				<codigos>B25-B49</codigos>
				<codigos>B58-B64</codigos>
				<codigos>B66-B94</codigos>
				<codigos>B99-B99</codigos>
				</item>
			</item>
		<item seq="1-026">
			<nome>Neoplasias</nome>
			<codigos>C00-D48</codigos>
			<item seq="1-027">
				<nome>Neoplasia maligna do lábio, cavidade oral e faringe</nome>
				<codigos>C00-C14</codigos>
				</item>
			<item seq="1-028">
				<nome>Neoplasia maligna do esôfago</nome>
				<codigos>C15-C15</codigos>
				</item>
			<item seq="1-029">
				<nome>Neoplasia maligna do estômago</nome>
				<codigos>C16-C16</codigos>
				</item>
			<item seq="1-030">
				<nome>Neoplasia maligna de cólon, reto e ânus</nome>
				<codigos>C18-C21</codigos>
				</item>
			<item seq="1-031">
				<nome>Neoplasia maligna do fígado e das vias biliais intra-hepáticas</nome>
				<codigos>C22-C22</codigos>
				</item>
			<item seq="1-032">
				<nome>Neoplasia maligna do pâncreas</nome>
				<codigos>C25-C25</codigos>
				</item>
			<item seq="1-033">
				<nome>Neoplasia maligna da laringe</nome>
				<codigos>C32-C32</codigos>
				</item>
			<item seq="1-034">
				<nome>Neoplasia maligna da traquéia, dos brônquios e dos pulmões</nome>
				<codigos>C33-C34</codigos>
				</item>
			<item seq="1-035">
				<nome>Neoplasia maligna da pele</nome>
				<codigos>C43-C43</codigos>
				</item>
			<item seq="1-036">
				<nome>Neoplasia maligna da mama</nome>
				<codigos>C50-C50</codigos>
				</item>
			<item seq="1-037">
				<nome>Neoplasia maligna do colo do útero</nome>
				<codigos>C53-C53</codigos>
				</item>
			<item seq="1-038">
				<nome>Neoplasia maligna de outras partes e de partes não especificadas do útero</nome>
				<codigos>C54-C55</codigos>
				</item>
			<item seq="1-039">
				<nome>Neoplasia maligna do ovário</nome>
				<codigos>C56-C56</codigos>
				</item>
			<item seq="1-040">
				<nome>Neoplasia maligna da próstata</nome>
				<codigos>C61-C61</codigos>
				</item>
			<item seq="1-041">
				<nome>Neoplasia maligna da bexiga</nome>
				<codigos>C67-C67</codigos>
				</item>
			<item seq="1-042">
				<nome>Neoplasia maligna as meninges, do encéfalo e de outras partes do sistema nervoso central</nome>
				<codigos>C70-C72</codigos>
				</item>
			<item seq="1-043">
				<nome>Linfoma não-Hodgkin</nome>
				<codigos>C82-C85</codigos>
				</item>
			<item seq="1-044">
				<nome>Mieloma múltiplo e neoplasias malignas de plasmócitos</nome>
				<codigos>C90-C90</codigos>
				</item>
			<item seq="1-045">
				<nome>Leucemia</nome>
				<codigos>C91-C95</codigos>
				</item>
			<item seq="1-046">
				<nome>Restante de neoplasias malignas</nome>
				<codigos>C17-C17</codigos>
				<codigos>C23-C24</codigos>
				<codigos>C26-C31</codigos>
				<codigos>C37-C41</codigos>
				<codigos>C44-C49</codigos>
				<codigos>C51-C52</codigos>
				<codigos>C57-C60</codigos>
				<codigos>C62-C66</codigos>
				<codigos>C68-C69</codigos>
				<codigos>C73-C81</codigos>
				<codigos>C88-C88</codigos>
				<codigos>C96-C97</codigos>
				</item>
			<item seq="1-047">
				<nome>Restante de neoplasias</nome>
				<codigos>D00-D48</codigos>
				</item>
			</item>
		<item seq="1-048">
			<nome>Doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários</nome>
			<codigos>D50-D89</codigos>
			<item seq="1-049">
				<nome>Anemias</nome>
				<codigos>D50-D64</codigos>
				</item>
			<item seq="1-050">
				<nome>Restante das doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários</nome>
				<codigos>D65-D89</codigos>
				</item>
			</item>
		<item seq="1-051">
			<nome>Doenças endrócrinas, nutrionais e metabólicas</nome>
			<codigos>E00-E88</codigos>
			<item seq="1-052">
				<nome>Diabetes mellitus</nome>
				<codigos>E10-E14</codigos>
				</item>
			<item seq="1-053">
				<nome>Desnutrição</nome>
				<codigos>E40-E46</codigos>
				</item>
			<item seq="1-054">
				<nome>Restante de doenças endócrinas, nutricionais e metabólicas</nome>
				<codigos>E00-E07</codigos>
				<codigos>E15-E34</codigos>
				<codigos>E50-E88</codigos>
				</item>
			</item>
		<item seq="1-055">
			<nome>Transtornos mentais e comportamentais</nome>
			<codigos>F01-F99</codigos>
			<item seq="1-056">
				<nome>Transtornos mentais e comportamentais devidos ao uso de substâncias psicoativas</nome>
				<codigos>F10-F19</codigos>
				</item>
			<item seq="1-057">
				<nome>Restante dos transtornos mentais e comportamentais</nome>
				<codigos>F01-F09</codigos>
				<codigos>F20-F99</codigos>
				</item>
			</item>
		<item seq="1-058">
			<nome>Doenças do sistema nervoso</nome>
			<codigos>G00-G98</codigos>
			<item seq="1-059">
				<nome>Meningite</nome>
				<codigos>G03-G03</codigos>
				</item>
			<item seq="1-060">
				<nome>Doença de Alzheimer</nome>
				<codigos>G30-G30</codigos>
				</item>
			<item seq="1-061">
				<nome>Restante das doenças do sistema nervoso</nome>
				<codigos>G04-G25</codigos>
				<codigos>G31-G98</codigos>
				</item>
			</item>
		<item seq="1-062">
			<nome>Doenças dos olhos e anexos</nome>
			<codigos>H00-H57</codigos>
			</item>
		<item seq="1-063">
			<nome>Doenças do ouvido e da apófise mastóide</nome>
			<codigos>H60-H93</codigos>
			</item>
		<item seq="1-064">
			<nome>Doenças do aparelho circulatório</nome>
			<codigos>I00-I99</codigos>
			<item seq="1-065">
				<nome>Febre reumática aguda e doença reumática crônica do coração</nome>
				<codigos>I00-I09</codigos>
				</item>
			<item seq="1-066">
				<nome>Doenças hipertensivas</nome>
				<codigos>I10-I13</codigos>
				</item>
			<item seq="1-067">
				<nome>Doenças isquêmicas do coração</nome>
				<codigos>I20-I25</codigos>
				</item>
			<item seq="1-068">
				<nome>Outras doenças cardíacas</nome>
				<codigos>I26-I51</codigos>
				</item>
			<item seq="1-069">
				<nome>Doenças cerebrovasculares</nome>
				<codigos>I60-I69</codigos>
				</item>
			<item seq="1-070">
				<nome>Aterosclerose</nome>
				<codigos>I70-I70</codigos>
				</item>
			<item seq="1-071">
				<nome>Restante de doenças do aparelho circulatório</nome>
				<codigos>I71-I99</codigos>
				</item>
			</item>
		<item seq="1-072">
			<nome>Doenças do aparelho circulatório</nome>
			<codigos>J00-J98</codigos>
			<item seq="1-073">
				<nome>Influenza [gripe]</nome>
				<codigos>J09-J11</codigos>
				</item>
			<item seq="1-074">
				<nome>Pneumonia</nome>
				<codigos>J12-J18</codigos>
				</item>
			<item seq="1-075">
				<nome>Outras infecções agudas das vias aéreas inferiores</nome>
				<codigos>J20-J22</codigos>
				</item>
